const colors = require('tailwindcss/colors')

module.exports = {
  experimental: {
    optimizeUniversalDefaults: true,
  },
  content: [
    './pages/**/*.js',
    './components/**/*.js',
    './layouts/**/*.js',
    './lib/**/*.js',
    './data/**/*.mdx',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      spacing: {
        '9/16': '56.25%',
      },
      lineHeight: {
        11: '2.75rem',
        12: '3rem',
        13: '3.25rem',
        14: '3.5rem',
      },
      fontFamily: {
        display: ['"Inter Tight"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        serif: ['"Inter Tight"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['"Inter Tight"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"Inter Tight"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        paper: 'var(--paper)',
        ink: 'var(--ink)',
        muted: 'var(--ink-muted)',
        rule: 'var(--rule)',
        accent: {
          DEFAULT: 'var(--accent)',
          hover: 'var(--accent-hover)',
        },
        signal: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        terracotta: {
          50: '#fef6f3',
          100: '#fdeae3',
          200: '#fbd4c7',
          300: '#f7b39e',
          400: '#f18a6d',
          500: '#D4745E',
          600: '#c55a3e',
          700: '#a6442f',
          800: '#88392a',
          900: '#6f3327',
        },
        stone: colors.stone,
        primary: {
          50: '#fdf2f4',
          100: '#fce7eb',
          200: '#f9d0d9',
          300: '#f4a8b8',
          400: '#ec7591',
          500: '#e0496e',
          600: '#8b2635',
          700: '#7a1f2d',
          800: '#661b28',
          900: '#571a26',
        },
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            fontSize: '1.05rem',
            lineHeight: '1.75',
            maxWidth: '42rem',
            color: 'var(--ink)',
            fontFamily: theme('fontFamily.serif').join(', '),
            '--tw-prose-body': 'var(--ink)',
            '--tw-prose-headings': 'var(--ink)',
            '--tw-prose-links': 'var(--ink)',
            '--tw-prose-bold': 'var(--ink)',
            '--tw-prose-counters': 'var(--ink-muted)',
            '--tw-prose-bullets': 'var(--ink-muted)',
            '--tw-prose-hr': 'var(--rule)',
            '--tw-prose-quotes': 'var(--ink)',
            '--tw-prose-quote-borders': 'var(--accent)',
            '--tw-prose-code': 'var(--ink)',
            '--tw-prose-code-bg': 'var(--paper-2)',
            a: {
              color: 'var(--ink)',
              textDecoration: 'underline',
              textDecorationThickness: '1px',
              textUnderlineOffset: '0.18em',
              fontWeight: '400',
              '&:hover': {
                color: 'var(--ink-muted)',
              },
            },
            h1: {
              fontFamily: theme('fontFamily.sans').join(', '),
              fontWeight: '400',
              letterSpacing: '-0.02em',
              color: 'var(--ink)',
              lineHeight: '1.2',
            },
            h2: {
              fontFamily: theme('fontFamily.sans').join(', '),
              fontWeight: '400',
              letterSpacing: '-0.015em',
              color: 'var(--ink)',
              marginTop: '2.4rem',
              marginBottom: '0.8rem',
            },
            h3: {
              fontFamily: theme('fontFamily.sans').join(', '),
              fontWeight: '400',
              color: 'var(--ink)',
            },
            h4: {
              fontFamily: theme('fontFamily.sans').join(', '),
              fontWeight: '400',
              color: 'var(--ink)',
            },
            code: {
              color: 'var(--ink)',
              backgroundColor: 'var(--paper-2)',
              paddingLeft: '5px',
              paddingRight: '5px',
              paddingTop: '2px',
              paddingBottom: '2px',
              borderRadius: '3px',
              fontWeight: '500',
              fontSize: '0.9em',
            },
            'code::before': {
              content: 'none',
            },
            'code::after': {
              content: 'none',
            },
            pre: {
              backgroundColor: '#1b1713',
              color: '#f0e9dc',
              borderRadius: '4px',
              padding: '1.35rem 1.5rem',
              code: {
                backgroundColor: 'transparent',
                color: 'inherit',
                padding: 0,
                fontWeight: '400',
              },
            },
            blockquote: {
              fontFamily: theme('fontFamily.sans').join(', '),
              fontStyle: 'italic',
              fontWeight: '400',
              borderLeftColor: 'var(--accent)',
              borderLeftWidth: '2px',
              color: 'var(--ink)',
              paddingLeft: '1.1rem',
            },
            p: {
              marginTop: '0',
              marginBottom: '1.25rem',
            },
            li: {
              marginTop: '0.4rem',
              marginBottom: '0.4rem',
            },
            hr: {
              borderColor: 'var(--rule)',
            },
          },
        },
        dark: {
          css: {
            color: 'var(--ink)',
            '--tw-prose-body': 'var(--ink)',
            '--tw-prose-headings': 'var(--ink)',
            '--tw-prose-links': 'var(--ink)',
            '--tw-prose-bold': 'var(--ink)',
            '--tw-prose-counters': 'var(--ink-muted)',
            '--tw-prose-bullets': 'var(--ink-muted)',
            '--tw-prose-hr': 'var(--rule)',
            '--tw-prose-quotes': 'var(--ink)',
            '--tw-prose-quote-borders': 'var(--accent)',
            '--tw-prose-code': 'var(--ink)',
            '--tw-prose-code-bg': 'var(--paper-2)',
            a: {
              color: 'var(--ink)',
              '&:hover': {
                color: 'var(--ink-muted)',
              },
            },
            h1: {
              color: 'var(--ink)',
            },
            h2: {
              color: 'var(--ink)',
            },
            h3: {
              color: 'var(--ink)',
            },
            h4: {
              color: 'var(--ink)',
            },
            code: {
              color: 'var(--ink)',
              backgroundColor: 'var(--paper-2)',
            },
            pre: {
              backgroundColor: '#0f0d0b',
              color: '#f0e9dc',
            },
            blockquote: {
              borderLeftColor: 'var(--accent)',
              color: 'var(--ink)',
            },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
}
